### PR TITLE
Fix poetry warnings

### PR DESCRIPTION
**Pull request by ken-matsui**
###### What's changed

* Poetry version has been bumped to `1.5.1`
* The `secondary` key for `source` is deprecated, used `priority` instead (cf. https://python-poetry.org/docs/repositories/#secondary-package-sources-deprecated)
* `secondary` value for the `priority` key is deprecated, used `supplemental` instead (cf. https://python-poetry.org/docs/repositories/#secondary-package-sources-deprecated)
* PyPI will be disabled, use added PyPI as a primary source (cf. https://python-poetry.org/docs/repositories/#default-package-source)

### CODE REVIEW

**Comment by samkaufman** [comment]
> PyPI will be disabled, use added PyPI as a primary source (cf. https://python-poetry.org/docs/repositories/#default-package-source)

Good catch. Since we're only grabbing PyTorch from that repository, maybe we should indicate that explicitly instead of adding PyPI, as in this example from the documentation:

```toml
[tool.poetry.dependencies]
...
httpx = { version = "^0.22", source = "internal-pypi" }

[[tool.poetry.source]]
name = "internal-pypi"
url = ...
priority = ...
```

**Comment by ken-matsui** [comment]
@samkaufman Is it correct that we want to fetch only `torch` from PyTorch? It seems that `torch` can be downloaded through PyPI. Related issue: https://github.com/python-poetry/poetry/issues/6409

```toml
torch = { version = "^1.12.1", source = "pytorch" }

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/torch/"
priority = "explicit"
```

```console
$ poetry lock
Updating dependencies
Resolving dependencies... (0.3s)Source (pytorch): Authorization error accessing https://download.pytorch.org/whl/torch/torch/
Resolving dependencies... (0.5s)

Because morello depends on torch (^1.12.1) which doesn't match any versions, version solving failed.
```

↓

```toml
torch = "^1.12.1"

#[[tool.poetry.source]]
#name = "pytorch"
#url = "https://download.pytorch.org/whl/torch/"
#priority = "supplemental"
```

```console
$ poetry lock
Updating dependencies
Resolving dependencies... (8.7s)

Writing lock file
```

---

There is a workaround, but I am unsure that we really want to do something like this:

https://github.com/python-poetry/poetry/issues/6409#issuecomment-1568061569

**Comment by samkaufman** [comment]
> Is it correct that we want to fetch only `torch` from PyTorch?

I believe so, yes. If we want to pull from PyPI, we should:

- [ ] Verify that package is identical. In particular, I would like to be sure all statically linked libraries (esp. any BLAS interfaces) are the same and that the code is built identically.
- [ ] Be sure we're getting the CPU-only package.

I'm not sure this is worth the effort. I'm all-in on future-proofing the poetry configuration and fixing that deprecated key warning, though.

**Also,** I'm pulled some package updates into the main branch, including an update to PyTorch 2, so we should rebase this PR.

**Comment by ken-matsui** [comment]
> I'm not sure this is worth the effort. I'm all-in on future-proofing the poetry configuration and fixing that deprecated key warning, though.

Agreed, and I think we do not want to work on this right now since this is not urgent but a bit tricky. So, I will work on this when I really have time. Thank you for your review!

**Comment by ken-matsui** [comment]
Close because of Rust migration

**Pull request closed without merging**
