### PR TITLE
Remove the definition for non-async function in gen_test.py

### PR DESCRIPTION
**Pull request by ken-matsui**
Might this be a syntax error brought when a merge? Or this might be correct...?

### CODE REVIEW

**Comment by samkaufman** [comment]
This is correct. Notice the test `await`s.

**Comment by ken-matsui** [comment]
@samkaufman Thank you for reviewing this! Just out of curiosity, why is there no need to indent the line?

**Comment by samkaufman** [comment]
@ken-matsui I'm not sure. Why would there be?

**Comment by samkaufman** [comment]
Oh, I see. I misread the diff. You're totally right and I've removed the line on main.

**Comment by ken-matsui** [comment]
Oh okay, thank you!

**Pull request closed without merging**
