### PR TITLE
Exit immediately on panic over threads

### PR DESCRIPTION
**Pull request by ken-matsui**
The current implementation does not finish the entire program even if any thread panics.  Since if panic happens, there is no benefit to continue, I updated the code to immediately exit on panic.

### CODE REVIEW

**Comment by samkaufman** [comment]
@ken-matsui As a safer alternative, can we use [panic_fuse](https://docs.rs/rayon/latest/rayon/iter/trait.ParallelIterator.html#method.panic_fuse)?

**Comment by ken-matsui** [comment]
@samkaufman I actually tried `panic_fuse`, but it did not work as expected. This might be because the deep recursion is preventing the synchronization.

**Comment by samkaufman** [comment]
I'd like to meet a few requirements:
- Since morello is a library, it would be good to avoid terminating the process, so that callers can handle panics if they'd like.
  - If we do terminate the process, we should avoid choosing an arbitrary error code. That error code (`1`) might have meaning to the binary.
- If we really need to assert that the database type is unwind-safe, let's make the assertion as precise as possible (by wrapping a small types) to reduce the likelihood that we introduce changes later which violate that assertion.

I think the ideal is to handle this like a rayon parallel iterator would: let a thread panic normally and propogate the panic to the caller. `par_fuse`, as I understand it, just sets an `AtomicBool` during panic-unwinding and checks it before future task launches. We could do something similar by forwarding an `AtomicBool` through all top_down and checking it as a first step in each `top_down_spec` call. (If we do, we should make sure the performance hit is negligible.)

However, I have to ask… would it be easier to just fix the panic you're running into, @ken-matsui?

**Comment by samkaufman** [comment]
It might also make sense for our binaries to be built with `panic='abort'`, at least for now.

**Comment by ken-matsui** [comment]
> I'd like to meet a few requirements:
> 
> * Since morello is a library, it would be good to avoid terminating the process, so that callers can handle panics if they'd like.
>   

My apologizes, I totally forgot Morello is a library!  I completely agree that we should not just exit the program.

>   * If we do terminate the process, we should avoid choosing an arbitrary error code. That error code (`1`) might have meaning to the binary.
> * If we really need to assert that the database type is unwind-safe, let's make the assertion as precise as possible (by wrapping a small types) to reduce the likelihood that we introduce changes later which violate that assertion.
> 
> I think the ideal is to handle this like a rayon parallel iterator would: let a thread panic normally and propogate the panic to the caller. `par_fuse`, as I understand it, just sets an `AtomicBool` during panic-unwinding and checks it before future task launches. We could do something similar by forwarding an `AtomicBool` through all top_down and checking it as a first step in each `top_down_spec` call. (If we do, we should make sure the performance hit is negligible.)
>

My intention for this patch was just usability so that users could quickly notice any problems.  So, I do not think it's worth updating the code and verifying the performance.

> However, I have to ask… would it be easier to just fix the panic you're running into, @ken-matsui?

Yes, I think it should be easier.

> It might also make sense for our binaries to be built with `panic='abort'`, at least for now.

If this is acceptable, I will update this patch.  Or, just closing this PR for now is also fine with me :)

**Pull request closed without merging**
